/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cafe_Management_System;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author RAVI RANJAN
 */
public class Cafe_Management_System extends javax.swing.JFrame {
    
    double[] drink = new double[5];
    double[] snack = new double[5];
    double[] cost = new double[3];
    double[] i = new double[10];
    double[] cost1 = new double[3];
    double[] customer=new double[2];
    int ref=7500;
    private String p;

    /**
     * Creates new form Cafe_Management_System
     */
    public Cafe_Management_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jChkHotCoffee = new javax.swing.JCheckBox();
        jChkColdCoffee = new javax.swing.JCheckBox();
        jChkTea = new javax.swing.JCheckBox();
        jChkColdDrink = new javax.swing.JCheckBox();
        jChkWaterBotle = new javax.swing.JCheckBox();
        jtxtHotCoffee = new javax.swing.JTextField();
        jtxtColdCoffee = new javax.swing.JTextField();
        jtxtTea = new javax.swing.JTextField();
        jtxtColdDrink = new javax.swing.JTextField();
        jtxtWaterBotle = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jbtnTotal = new javax.swing.JButton();
        jbtnReceipt = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jChkSamosa = new javax.swing.JCheckBox();
        jChkLitti = new javax.swing.JCheckBox();
        jChkChat = new javax.swing.JCheckBox();
        jChkMomos = new javax.swing.JCheckBox();
        jChkChips = new javax.swing.JCheckBox();
        jtxtSamosa = new javax.swing.JTextField();
        jtxtLitti = new javax.swing.JTextField();
        jtxtChat = new javax.swing.JTextField();
        jtxtMomos = new javax.swing.JTextField();
        jtxtChips = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlblTax = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jtableno = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlblCostDrink = new javax.swing.JLabel();
        jlblCostSnacks = new javax.swing.JLabel();
        jlblService = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtcustomername = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jtxtcontactno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Refresh_Point");

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafe_Management_System/sign out copy.png"))); // NOI18N
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPreferredSize(new java.awt.Dimension(87, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafe_Management_System/Screenshot (10) copy2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 422, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 90));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Beverages", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial Rounded MT Bold", 1, 24))); // NOI18N

        jChkHotCoffee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jChkHotCoffee.setText("Hot Coffee");
        jChkHotCoffee.setPreferredSize(new java.awt.Dimension(95, 20));
        jChkHotCoffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkHotCoffeeMouseClicked(evt);
            }
        });
        jChkHotCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkHotCoffeeActionPerformed(evt);
            }
        });

        jChkColdCoffee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jChkColdCoffee.setText("Cold Coffee");
        jChkColdCoffee.setPreferredSize(new java.awt.Dimension(97, 32));
        jChkColdCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkColdCoffeeActionPerformed(evt);
            }
        });

        jChkTea.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jChkTea.setText("Tea");
        jChkTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkTeaActionPerformed(evt);
            }
        });

        jChkColdDrink.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jChkColdDrink.setText("Cold Drinks");
        jChkColdDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkColdDrinkActionPerformed(evt);
            }
        });

        jChkWaterBotle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jChkWaterBotle.setText("Water Bottle");
        jChkWaterBotle.setPreferredSize(new java.awt.Dimension(105, 28));
        jChkWaterBotle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkWaterBotleActionPerformed(evt);
            }
        });

        jtxtHotCoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtHotCoffee.setText("0");
        jtxtHotCoffee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jtxtHotCoffee.setFocusCycleRoot(true);
        jtxtHotCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtHotCoffeeActionPerformed(evt);
            }
        });
        jtxtHotCoffee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtHotCoffeeKeyTyped(evt);
            }
        });

        jtxtColdCoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtColdCoffee.setText("0");
        jtxtColdCoffee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jtxtColdCoffee.setFocusCycleRoot(true);
        jtxtColdCoffee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtColdCoffeeKeyTyped(evt);
            }
        });

        jtxtTea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTea.setText("0");
        jtxtTea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jtxtTea.setFocusCycleRoot(true);
        jtxtTea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTeaKeyTyped(evt);
            }
        });

        jtxtColdDrink.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtColdDrink.setText("0");
        jtxtColdDrink.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jtxtColdDrink.setFocusCycleRoot(true);
        jtxtColdDrink.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtColdDrinkKeyTyped(evt);
            }
        });

        jtxtWaterBotle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtWaterBotle.setText("0");
        jtxtWaterBotle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jtxtWaterBotle.setFocusCycleRoot(true);
        jtxtWaterBotle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtWaterBotleActionPerformed(evt);
            }
        });
        jtxtWaterBotle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtWaterBotleKeyTyped(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("15.00");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("20.00");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("10.00");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("15.00");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("10.00");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Item");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Rate");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Quantity");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jChkWaterBotle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkColdDrink)
                    .addComponent(jChkTea, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jChkColdCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jChkHotCoffee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)))
                .addGap(80, 80, 80)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jtxtWaterBotle)
                    .addComponent(jtxtColdCoffee)
                    .addComponent(jtxtTea)
                    .addComponent(jtxtHotCoffee)
                    .addComponent(jtxtColdDrink))
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jChkHotCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChkColdCoffee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChkTea, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jChkColdDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtHotCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtColdCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtTea, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtColdDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtWaterBotle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jChkWaterBotle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 440, 340));

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jbtnTotal.setBackground(new java.awt.Color(0, 153, 153));
        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        jbtnReceipt.setBackground(new java.awt.Color(0, 153, 153));
        jbtnReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnReceipt.setText("Receipt");
        jbtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReceiptActionPerformed(evt);
            }
        });

        jbtnReset.setBackground(new java.awt.Color(0, 153, 153));
        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnExit.setBackground(new java.awt.Color(0, 153, 153));
        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnExit.setText("Print");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnReceipt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 560, 370, 80));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Snacks", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial Rounded MT Bold", 1, 24))); // NOI18N

        jChkSamosa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jChkSamosa.setText("Samosa");
        jChkSamosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkSamosaActionPerformed(evt);
            }
        });

        jChkLitti.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jChkLitti.setText("Burger");
        jChkLitti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkLittiActionPerformed(evt);
            }
        });

        jChkChat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jChkChat.setText("Sandwich");
        jChkChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkChatActionPerformed(evt);
            }
        });

        jChkMomos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jChkMomos.setText("Momos");
        jChkMomos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkMomosActionPerformed(evt);
            }
        });

        jChkChips.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jChkChips.setText("Pasta");
        jChkChips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkChipsActionPerformed(evt);
            }
        });

        jtxtSamosa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtSamosa.setText("0");
        jtxtSamosa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jtxtSamosa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtSamosa.setDragEnabled(true);
        jtxtSamosa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtSamosaKeyTyped(evt);
            }
        });

        jtxtLitti.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtLitti.setText("0");
        jtxtLitti.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jtxtLitti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtLittiKeyTyped(evt);
            }
        });

        jtxtChat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChat.setText("0");
        jtxtChat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jtxtChat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtChatKeyTyped(evt);
            }
        });

        jtxtMomos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtMomos.setText("0");
        jtxtMomos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jtxtMomos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtMomosKeyTyped(evt);
            }
        });

        jtxtChips.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChips.setText("0");
        jtxtChips.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jtxtChips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChipsActionPerformed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("8.00");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("15.00");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("15.00");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("20.00");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("15.00");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Item");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Rate");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Quantity");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jChkMomos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jChkChips, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jChkChat))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jChkLitti, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(90, 90, 90))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jChkSamosa)
                                    .addGap(80, 80, 80)))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtChat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtMomos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtChips, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSamosa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtLitti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkSamosa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSamosa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkLitti, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtLitti, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkChat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtChat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkMomos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtMomos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkChips, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtChips, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 420, 340));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0), 3));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        jLabel6.setText("GST ");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        jLabel7.setText("  Sub Total");

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        jLabel8.setText("  Total");

        jlblTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTax.setText("0");
        jlblTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSubTotal.setText("0");
        jlblSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTotal.setText("0");
        jlblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Table no");

        jtableno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtableno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtableno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtableno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtablenoMouseReleased(evt);
            }
        });
        jtableno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtablenoActionPerformed(evt);
            }
        });
        jtableno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtablenoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jlblTax, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jtableno))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jtableno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblSubTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 420, 200));

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jtxtReceipt.setEditable(false);
        jtxtReceipt.setColumns(20);
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, 370, 460));

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0), 3));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Cost of Beverages");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("  Cost Of Snacks");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Service charge");

        jlblCostDrink.setBackground(new java.awt.Color(255, 255, 255));
        jlblCostDrink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblCostDrink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCostDrink.setText("0");
        jlblCostDrink.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblCostSnacks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblCostSnacks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCostSnacks.setText("0");
        jlblCostSnacks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblService.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblService.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblService.setText("5.0");
        jlblService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Customer Name");

        jtxtcustomername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtcustomername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jtxtcustomername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcustomernameActionPerformed(evt);
            }
        });
        jtxtcustomername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcustomernameKeyTyped(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Contact No");

        jtxtcontactno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtcontactno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jtxtcontactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcontactnoActionPerformed(evt);
            }
        });
        jtxtcontactno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcontactnoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblCostDrink, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jlblCostSnacks, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jlblService, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jtxtcustomername, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jtxtcontactno, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCostDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCostSnacks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblService, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtcustomername))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jtxtcontactno, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 440, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtxtcontactno.setText(" ");
        jtxtcustomername.setText(" ");
        jlblCostSnacks.setText("0");
        jlblCostDrink.setText("0");
        //jlblService.setText("0");
        jtableno.setText(" ");
        jlblTax.setText("0");
        jlblSubTotal.setText("0");
        jlblTotal.setText("0");
        jtxtHotCoffee.setText("0");
        jtxtColdCoffee.setText("0");
        jtxtTea.setText("0");
        jtxtWaterBotle.setText("0");
        jtxtColdDrink.setText("0");
        jtxtSamosa.setText("0");
        jtxtLitti.setText("0");
        jtxtChat.setText("0");
        jtxtMomos.setText("0");
        jtxtChips.setText("0");
        jtxtReceipt.setText(null);
        jChkHotCoffee.setSelected(false);
        jChkColdCoffee.setSelected(false);
        jChkTea.setSelected(false);
        jChkWaterBotle.setSelected(false);
        jChkColdDrink.setSelected(false);
        jChkSamosa.setSelected(false);
        jChkLitti.setSelected(false);
        jChkMomos.setSelected(false);
        jChkChips.setSelected(false);
        jChkChat.setSelected(false);
        jbtnReceipt.setEnabled(true);
        jtxtHotCoffee.setEditable(true);
        jtxtColdCoffee.setEditable(true);
        jtxtTea.setEditable(true);
        jtxtColdDrink.setEditable(true);
        jtxtWaterBotle.setEditable(true);
        jbtnTotal.setEnabled(true);
        
         
        
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        try {
            //System.exit(0);
            jtxtReceipt.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Cafe_Management_System.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReceiptActionPerformed
        // TODO add your handling code here:
        ref=ref+1;
       // p=jtxtcustomername.getText().toString();
       // customer[1]=Double.parseDouble(jtxtcontactno.getText());
        
            
        if(jtableno.getText().equals("") && jtxtcustomername.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "input a user details first.");
        }
        
        
        jtxtReceipt.setText("==========================================================================\n");
        jtxtReceipt.setText("\t- REFRESH_POINT -\n\n Book Your Freshen Table: www.vksu/refreshpoint.com\n");
        jtxtReceipt.setText(jtxtReceipt.getText()+"---------------------------------------------------------------\n");
        jtxtReceipt.setText(jtxtReceipt.getText()+"Customer Name:\t"+jtxtcustomername.getText()+"\n");
        jtxtReceipt.setText(jtxtReceipt.getText()+"Table no:\t\t"+jtableno.getText()+"\n");
        jtxtReceipt.setText(jtxtReceipt.getText()+"Contact N0 :\t\t+91"+jtxtcontactno.getText()+"\n");
        drink[0] = Double.parseDouble(jtxtHotCoffee.getText());
        drink[1] = Double.parseDouble(jtxtColdCoffee.getText());
        drink[2] = Double.parseDouble(jtxtTea.getText());
        drink[3] = Double.parseDouble(jtxtColdDrink.getText());
        drink[4] = Double.parseDouble(jtxtWaterBotle.getText());
        
        snack[0] = Double.parseDouble(jtxtSamosa.getText());
        snack[1] = Double.parseDouble(jtxtLitti.getText());
        snack[2] = Double.parseDouble(jtxtChat.getText());
        snack[3] = Double.parseDouble(jtxtMomos.getText());
        snack[4] = Double.parseDouble(jtxtChips.getText());
        cost[0] = Double.parseDouble(jlblTax.getText());
        cost[1] = Double.parseDouble(jlblSubTotal.getText());
        cost[2] = Double.parseDouble(jlblTotal.getText());
        cost1[0] =Double.parseDouble(jlblCostDrink.getText());
        cost1[1] =Double.parseDouble(jlblCostSnacks.getText());
        cost1[2] =Double.parseDouble(jlblService.getText());
        
        //====================================================================
        //int refs;
        //refs = 1325 + (int) (Math.random() * 4238);
        //int ref = (refs);
        //===================================================================
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MM-YYY");
        Tdate.format(timer.getTime());
        //====================================================================

        jtxtReceipt.append("  "
                
                + "Reference:\t\t" + ref
                +"\n Customer Type: \tRegular \n" 
               
                + "\n====================================\n"
                +"\t===Beverages===\n\n "
                + "Item \t Quantity  \tRate:\n"
                + "Hot Coffee: \t " + drink[0] + "\t15.00 "
                + "\nCold Coffee: \t " + drink[1] + "\t20.00 "
                + "\nTea: \t " + drink[2] + "\t10.00 "
                + "\nCold Drink: \t " + drink[3] + "\t15.00 "
                + "\nWater Bottle: \t " + drink[4] + "\t10.00 "
                + "\n"
                +"\n\t===Snacks=== \n"
                + "\nItem \t Quantity\tRate:"
                + "\nSamosa: \t " + snack[0] + "\t8.00 "
                + "\nBurger: \t " + snack[1] + "\t15.00 "
                + "\nSandwich: \t " + snack[2] + "\t15.00 "
                + "\nMomos: \t " + snack[3] + "\t20.00 "
                + "\nPasta: \t " + snack[4] + "\t15.00 "
                + "\n====================================\t\t"
                +"\nCost of Beverages:\t "+ cost1[0]
                +"\nCost of Snacks: \t "+ cost1[1]
                +"\nService Charge: \t "+ cost1[2]
                + "\nGST: \t\t " + cost[0]
                + "\nSub Total: \t\t " + cost[1]
                + "\nTotal: \t\t " + cost[2]
                + "\n----------------------------------------------------------------\t\t"
                + "\nDate:" + Tdate.format(timer.getTime())
                + "\tTime: " + tTime.format(timer.getTime())
                + "\n\n Your Happiness is our Priority. \nThank You , Visit Again !!!");
        
        jbtnReceipt.setEnabled(false);

    }//GEN-LAST:event_jbtnReceiptActionPerformed

    private void jChkHotCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkHotCoffeeActionPerformed
        //double cHotCoffee = Double.parseDouble(jlblCostDrink.getText());
        //double HotCoffee = Double.parseDouble(jtxtHotCoffee.getText());
        //double iHotCoffee = 10.00;
        float cnt;
        try {
            if (jChkHotCoffee.isSelected()) {
                //int cnt= Integer.parseInt(jtxtHotCoffee.getText());
                //cnt=(Integer.parseInt(jlblRateHotCoffee.getText()) *cnt) + Integer.parseInt(jlblCostDrink.getText());
                cnt = Float.parseFloat(jtxtHotCoffee.getText());
                cnt = (Float.parseFloat(jLabel9.getText()) * cnt) + Float.parseFloat(jlblCostDrink.getText());
                jlblCostDrink.setText(String.valueOf(cnt));
                jtxtHotCoffee.setEditable(false);
            } else {
                cnt = Float.parseFloat(jtxtHotCoffee.getText());
                cnt = (Float.parseFloat(jlblCostDrink.getText()) - Float.parseFloat(jLabel9.getText()) * cnt);
                jlblCostDrink.setText(String.valueOf(cnt));
                jtxtHotCoffee.setEditable(true);
                jtxtHotCoffee.setText("0");
            }
        } catch (Exception e) {
            e.fillInStackTrace();
        }
        

    }//GEN-LAST:event_jChkHotCoffeeActionPerformed

    private void jChkColdCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkColdCoffeeActionPerformed
        float cnt;
        try {
            if (jChkColdCoffee.isSelected()) {
                //int cnt= Integer.parseInt(jtxtHotCoffee.getText());
                //cnt=(Integer.parseInt(jlblRateHotCoffee.getText()) *cnt) + Integer.parseInt(jlblCostDrink.getText());
                cnt = Float.parseFloat(jtxtColdCoffee.getText());
                cnt = (Float.parseFloat(jLabel10.getText()) * cnt) + Float.parseFloat(jlblCostDrink.getText());
                jlblCostDrink.setText(String.valueOf(cnt));
                jtxtColdCoffee.setEditable(false);
            } else {
                cnt = Float.parseFloat(jtxtColdCoffee.getText());
                cnt = Float.parseFloat(jlblCostDrink.getText()) - Float.parseFloat(jLabel10.getText()) * cnt ;
                jlblCostDrink.setText(String.valueOf(cnt));
                jtxtColdCoffee.setEditable(true);
                jtxtColdCoffee.setText("0");
            }
        } catch (Exception e) {
            e.fillInStackTrace();
        }
    }//GEN-LAST:event_jChkColdCoffeeActionPerformed

    private void jChkHotCoffeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkHotCoffeeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkHotCoffeeMouseClicked

    private void jChkTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkTeaActionPerformed
      float cnt;
        try {
            if (jChkTea.isSelected()) {
                //int cnt= Integer.parseInt(jtxtHotCoffee.getText());
                //cnt=(Integer.parseInt(jlblRateHotCoffee.getText()) *cnt) + Integer.parseInt(jlblCostDrink.getText());
                cnt = Float.parseFloat(jtxtTea.getText());
                cnt = (Float.parseFloat(jLabel11.getText()) * cnt) + Float.parseFloat(jlblCostDrink.getText());
                jlblCostDrink.setText(String.valueOf(cnt));
                jtxtTea.setEditable(false);
            } else {
                cnt = Float.parseFloat(jtxtTea.getText());
                cnt = Float.parseFloat(jlblCostDrink.getText())-Float.parseFloat(jLabel11.getText()) * cnt;
                jlblCostDrink.setText(String.valueOf(cnt));
                jtxtTea.setEditable(true);
                jtxtTea.setText("0");
            }
        } catch (Exception e) {
            e.fillInStackTrace();
        }
    }//GEN-LAST:event_jChkTeaActionPerformed

    private void jChkColdDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkColdDrinkActionPerformed
   float cnt;
        try {
            if (jChkColdDrink.isSelected()) {
                //int cnt= Integer.parseInt(jtxtHotCoffee.getText());
                //cnt=(Integer.parseInt(jlblRateHotCoffee.getText()) *cnt) + Integer.parseInt(jlblCostDrink.getText());
                cnt = Float.parseFloat(jtxtColdDrink.getText());
                cnt = (Float.parseFloat(jLabel12.getText()) * cnt) + Float.parseFloat(jlblCostDrink.getText());
                jlblCostDrink.setText(String.valueOf(cnt));
                jtxtColdDrink.setEditable(false);
            } else {
                cnt = Float.parseFloat(jtxtColdDrink.getText());
                cnt = Float.parseFloat(jlblCostDrink.getText())-Float.parseFloat(jLabel12.getText()) * cnt  ;
                jlblCostDrink.setText(String.valueOf(cnt));
                jtxtColdDrink.setEditable(true);
                jtxtColdDrink.setText("0");
            }
        } catch (Exception e) {
            e.fillInStackTrace();
        }
    }//GEN-LAST:event_jChkColdDrinkActionPerformed

    private void jChkWaterBotleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkWaterBotleActionPerformed
       float cnt;
        try {
            if (jChkWaterBotle.isSelected()) {
                //int cnt= Integer.parseInt(jtxtHotCoffee.getText());
                //cnt=(Integer.parseInt(jlblRateHotCoffee.getText()) *cnt) + Integer.parseInt(jlblCostDrink.getText());
                cnt = Float.parseFloat(jtxtWaterBotle.getText());
                cnt = (Float.parseFloat(jLabel13.getText()) * cnt) + Float.parseFloat(jlblCostDrink.getText());
                jlblCostDrink.setText(String.valueOf(cnt));
                jtxtWaterBotle.setEditable(false);
            } else {
                cnt = Float.parseFloat(jtxtWaterBotle.getText());
                cnt = Float.parseFloat(jlblCostDrink.getText())-Float.parseFloat(jLabel13.getText()) * cnt;
                jlblCostDrink.setText(String.valueOf(cnt));
                jtxtWaterBotle.setEditable(true);
                jtxtWaterBotle.setText("0");
            }
        } catch (Exception e) {
            e.fillInStackTrace();
        }
    }//GEN-LAST:event_jChkWaterBotleActionPerformed

    private void jChkSamosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkSamosaActionPerformed
      float cnt;
        try {
            if (jChkSamosa.isSelected()) {
                //int cnt= Integer.parseInt(jtxtHotCoffee.getText());
                //cnt=(Integer.parseInt(jlblRateHotCoffee.getText()) *cnt) + Integer.parseInt(jlblCostDrink.getText());
                cnt = Float.parseFloat(jtxtSamosa.getText());
                cnt = (Float.parseFloat(jLabel14.getText()) * cnt) + Float.parseFloat(jlblCostSnacks.getText());
                jlblCostSnacks.setText(String.valueOf(cnt));
                jtxtSamosa.setEditable(false);
            } else {
                cnt = Float.parseFloat(jtxtSamosa.getText());
                cnt = Float.parseFloat(jlblCostSnacks.getText())-Float.parseFloat(jLabel14.getText()) * cnt;
                jlblCostSnacks.setText(String.valueOf(cnt));
                jtxtSamosa.setEditable(true);
                jtxtSamosa.setText("0");
            }
        } catch (Exception e) {
            e.fillInStackTrace();
        }  
    }//GEN-LAST:event_jChkSamosaActionPerformed

    private void jChkLittiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkLittiActionPerformed
    float cnt;
        try {
            if (jChkLitti.isSelected()) {
                //int cnt= Integer.parseInt(jtxtHotCoffee.getText());
                //cnt=(Integer.parseInt(jlblRateHotCoffee.getText()) *cnt) + Integer.parseInt(jlblCostDrink.getText());
                cnt = Float.parseFloat(jtxtLitti.getText());
                cnt = (Float.parseFloat(jLabel15.getText()) * cnt) + Float.parseFloat(jlblCostSnacks.getText());
                jlblCostSnacks.setText(String.valueOf(cnt));
                jtxtLitti.setEditable(false);
            } else {
                cnt = Float.parseFloat(jtxtLitti.getText());
                cnt =  Float.parseFloat(jlblCostSnacks.getText())- Float.parseFloat(jLabel15.getText()) * cnt;
                jlblCostSnacks.setText(String.valueOf(cnt));
                jtxtLitti.setEditable(true);
                jtxtLitti.setText("0");
            }
        } catch (Exception e) {
            e.fillInStackTrace();
        }  
    }//GEN-LAST:event_jChkLittiActionPerformed

    private void jChkChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkChatActionPerformed
       float cnt;
        try {
            if (jChkChat.isSelected()) {
                //int cnt= Integer.parseInt(jtxtHotCoffee.getText());
                //cnt=(Integer.parseInt(jlblRateHotCoffee.getText()) *cnt) + Integer.parseInt(jlblCostDrink.getText());
                cnt = Float.parseFloat(jtxtChat.getText());
                cnt = (Float.parseFloat(jLabel16.getText()) * cnt) + Float.parseFloat(jlblCostSnacks.getText());
                jlblCostSnacks.setText(String.valueOf(cnt));
                jtxtChat.setEditable(false);
            } else {
                cnt = Float.parseFloat(jtxtChat.getText());
                cnt = Float.parseFloat(jlblCostSnacks.getText()) - Float.parseFloat(jLabel16.getText()) * cnt; 
                jlblCostSnacks.setText(String.valueOf(cnt));
                jtxtChat.setEditable(true);
                jtxtChat.setText("0");
            }
        } catch (Exception e) {
            e.fillInStackTrace();
        }  
    }//GEN-LAST:event_jChkChatActionPerformed

    private void jChkMomosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkMomosActionPerformed
     float cnt;
        try {
            if (jChkMomos.isSelected()) {
                //int cnt= Integer.parseInt(jtxtHotCoffee.getText());
                //cnt=(Integer.parseInt(jlblRateHotCoffee.getText()) *cnt) + Integer.parseInt(jlblCostDrink.getText());
                cnt = Float.parseFloat(jtxtMomos.getText());
                cnt = (Float.parseFloat(jLabel17.getText()) * cnt) + Float.parseFloat(jlblCostSnacks.getText());
                jlblCostSnacks.setText(String.valueOf(cnt));
                jtxtMomos.setEditable(false);
            } else {
                cnt = Float.parseFloat(jtxtMomos.getText());
                cnt = Float.parseFloat(jlblCostSnacks.getText()) - Float.parseFloat(jLabel17.getText()) * cnt;
                jlblCostSnacks.setText(String.valueOf(cnt));
                jtxtMomos.setEditable(true);
                jtxtMomos.setText("0");
            }
        } catch (Exception e) {
            e.fillInStackTrace();
        }  
    }//GEN-LAST:event_jChkMomosActionPerformed

    private void jChkChipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkChipsActionPerformed
    float cnt;
        try {
            if (jChkChips.isSelected()) {
                //int cnt= Integer.parseInt(jtxtHotCoffee.getText());
                //cnt=(Integer.parseInt(jlblRateHotCoffee.getText()) *cnt) + Integer.parseInt(jlblCostDrink.getText());
                cnt = Float.parseFloat(jtxtChips.getText());
                cnt = (Float.parseFloat(jLabel18.getText()) * cnt) + Float.parseFloat(jlblCostSnacks.getText());
                jlblCostSnacks.setText(String.valueOf(cnt));
                jtxtChips.setEditable(false);
            } else {
                cnt = Float.parseFloat(jtxtChips.getText());
                cnt = Float.parseFloat(jlblCostSnacks.getText()) - Float.parseFloat(jLabel18.getText()) * cnt; 
                jlblCostSnacks.setText(String.valueOf(cnt));
                jtxtChips.setEditable(true);
                jtxtChips.setText("0");
            }
        } catch (Exception e) {
            e.fillInStackTrace();
        }   
    }//GEN-LAST:event_jChkChipsActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        // TODO add your handling code here:
        if(jlblCostDrink.getText().equals("0") && jlblCostSnacks.getText().equals("0")){
            JOptionPane.showMessageDialog(null, "Select a item first.");
            return;
        }
        float subTotal=Float.parseFloat(jlblCostDrink.getText())+Float.parseFloat(jlblCostSnacks.getText())+ Float.parseFloat(jlblService.getText());
        jlblSubTotal.setText(String.valueOf(subTotal));
        
        float tax=subTotal*5/100;
        jlblTax.setText(String.valueOf(tax));
        
        jlblTotal.setText(String.valueOf(subTotal + tax));
       
        
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jtxtHotCoffeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtHotCoffeeKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if(jtxtHotCoffee.getText().length()>=3){
            evt.consume();
        }
        if(c==KeyEvent.VK_ENTER){
            jtxtColdCoffee.requestFocus();
        }
        if(Character.isDigit(c)){}
        else{
            evt.consume();
            return;
        }
    }//GEN-LAST:event_jtxtHotCoffeeKeyTyped

    private void jtxtColdCoffeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtColdCoffeeKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if(jtxtColdCoffee.getText().length()>=3){
            evt.consume();
        }
        if(c==KeyEvent.VK_ENTER){
            jtxtTea.requestFocus();
        }
        if(Character.isDigit(c)){}
        else{
            evt.consume();
            return;
        }
    }//GEN-LAST:event_jtxtColdCoffeeKeyTyped

    private void jtxtTeaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTeaKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if(jtxtTea.getText().length()>=3){
            evt.consume();
        }
        if(c==KeyEvent.VK_ENTER){
            jtxtColdDrink.requestFocus();
        }
        if(Character.isDigit(c)){}
        else{
            evt.consume();
            return;
        }
    }//GEN-LAST:event_jtxtTeaKeyTyped

    private void jtxtColdDrinkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtColdDrinkKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if(jtxtColdDrink.getText().length()>=3){
            evt.consume();
        }
        if(c==KeyEvent.VK_ENTER){
            jtxtWaterBotle.requestFocus();
        }
        if(Character.isDigit(c)){}
        else{
            evt.consume();
            return;
        }
    }//GEN-LAST:event_jtxtColdDrinkKeyTyped

    private void jtxtWaterBotleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtWaterBotleKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if(jtxtWaterBotle.getText().length()>=3){
            evt.consume();
        }
        if(c==KeyEvent.VK_ENTER){
            jtxtSamosa.requestFocus();
        }
        if(Character.isDigit(c)){}
        else{
            evt.consume();
            return;
        }
    }//GEN-LAST:event_jtxtWaterBotleKeyTyped

    private void jtxtSamosaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSamosaKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if(jtxtSamosa.getText().length()>=3){
            evt.consume();
        }
        if(c==KeyEvent.VK_ENTER){
            jtxtLitti.requestFocus();
        }
        if(Character.isDigit(c)){}
        else{
            evt.consume();
            return;
        }
    }//GEN-LAST:event_jtxtSamosaKeyTyped

    private void jtxtLittiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtLittiKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if(jtxtLitti.getText().length()>=3){
            evt.consume();
        }
        if(c==KeyEvent.VK_ENTER){
            jtxtChat.requestFocus();
        }
        if(Character.isDigit(c)){}
        else{
            evt.consume();
            return;
        }
    }//GEN-LAST:event_jtxtLittiKeyTyped

    private void jtxtChatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChatKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if(jtxtChat.getText().length()>=3){
            evt.consume();
        }
        if(c==KeyEvent.VK_ENTER){
            jtxtMomos.requestFocus();
        }
        if(Character.isDigit(c)){}
        else{
            evt.consume();
            return;
        }
    }//GEN-LAST:event_jtxtChatKeyTyped

    private void jtxtMomosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMomosKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if(jtxtMomos.getText().length()>=3){
            evt.consume();
        }
        if(c==KeyEvent.VK_ENTER){
            jtxtChips.requestFocus();
        }
        if(Character.isDigit(c)){}
        else{
            evt.consume();
            return;
        }
    }//GEN-LAST:event_jtxtMomosKeyTyped

    private void jtxtcontactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcontactnoActionPerformed
        // TODO add your handling code here:
       // float cnt;

      //cnt = Float.parseFloat(jtxtcontactno.getText());
    }//GEN-LAST:event_jtxtcontactnoActionPerformed

    private void jtxtcustomernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcustomernameActionPerformed


     // p = jtxtcustomername.getText().toString();
    }//GEN-LAST:event_jtxtcustomernameActionPerformed

    private void jtxtWaterBotleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtWaterBotleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtWaterBotleActionPerformed

    private void jtxtcustomernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcustomernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcustomernameKeyTyped

    private void jtxtcontactnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcontactnoKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if(jtxtcontactno.getText().length()>=10){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtcontactnoKeyTyped

    private void jtxtHotCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHotCoffeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtHotCoffeeActionPerformed
   
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Loginform().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtablenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtablenoKeyTyped
        // TODO add your handling code here:
        char d= evt.getKeyChar();
        if(jtableno.getText().length()>=1){
            evt.consume();
        }
    }//GEN-LAST:event_jtablenoKeyTyped

    private void jtxtChipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChipsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChipsActionPerformed

    private void jtablenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtablenoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtablenoActionPerformed

    private void jtablenoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablenoMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtablenoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafe_Management_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jChkChat;
    private javax.swing.JCheckBox jChkChips;
    private javax.swing.JCheckBox jChkColdCoffee;
    private javax.swing.JCheckBox jChkColdDrink;
    private javax.swing.JCheckBox jChkHotCoffee;
    private javax.swing.JCheckBox jChkLitti;
    private javax.swing.JCheckBox jChkMomos;
    private javax.swing.JCheckBox jChkSamosa;
    private javax.swing.JCheckBox jChkTea;
    private javax.swing.JCheckBox jChkWaterBotle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReceipt;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JLabel jlblCostDrink;
    private javax.swing.JLabel jlblCostSnacks;
    private javax.swing.JLabel jlblService;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JTextField jtableno;
    private javax.swing.JTextField jtxtChat;
    private javax.swing.JTextField jtxtChips;
    private javax.swing.JTextField jtxtColdCoffee;
    private javax.swing.JTextField jtxtColdDrink;
    private javax.swing.JTextField jtxtHotCoffee;
    private javax.swing.JTextField jtxtLitti;
    private javax.swing.JTextField jtxtMomos;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtSamosa;
    private javax.swing.JTextField jtxtTea;
    private javax.swing.JTextField jtxtWaterBotle;
    private javax.swing.JTextField jtxtcontactno;
    private javax.swing.JTextField jtxtcustomername;
    // End of variables declaration//GEN-END:variables
}
